/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Publicaciones } from './publicaciones';
import { Usuario } from './usuario';

export interface Persona { 
    apellido?: string;
    edad?: string;
    email?: string;
    foto?: string;
    id?: number;
    nombre?: string;
    pais?: string;
    publicaciones?: Array<Publicaciones>;
    usuario?: Array<Usuario>;
}